# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CoderDojoすぎなみ
email: info@coderdojo-suginami.doorkeeper.jp
description:
  杉並区にある子どもたちのためのプログラミング倶楽部です。参加費は無料。プログラミング教室ではなく「自主学習」を支援します。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coderdojo-suginami.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

permalink: /events/:year/:month/:day/
timezone: Asia/Tokyo
future: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "vendor"]
